### ISSUE TITLE
Mobile Theming (English)

### ISSUE THREAD

**Issue by sukwhanchung** [PeaceGeeksSociety/Aid-Watch#14]
1. users can't switch language version
2. user can't access the sub-menus
3. i feel like it should be Subscribe | Take action |Follow Us then the icons (have the words together, then the icons? looks funny broken up like this to me. 
4. The main page titles and sub-titles need to be reduced in some places - http://dev.awptheme.peacegeeks.org/content/who-actually-responsible-reconstructing-gaza
5. On iPhone, the menu icon overlaps with the logo
6. The footer dividers are too tall, and the menu text is too small
7. The Resources icons turn blue and don't click thru

**Comment by PeaceGeeks** [comment]
Left to do 

(required for launch)
1. user can't access the sub-menus 

(nice-to-have)
2. The main page titles and sub-titles need to be reduced in some places - http://dev.awptheme.peacegeeks.org/content/who-actually-responsible-reconstructing-gaza
3. i feel like it should be Subscribe | Take action |Follow Us then the icons (have the words together, then the icons? looks funny broken up like this to me.
4. The Resources icons turn blue and don't click thru
