### ISSUE TITLE
Header images are cropping poorly

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/Aid-Watch#16]
It seems like some of the photos are cropping at funny places. See this page as an example. http://dev.awptheme.peacegeeks.org/about/our-accountability

Not sure what the best way to handle this is, but what about using a cropper tool so that the user can select the portion of the image that works best for the header?

**Comment by beyondes** [comment]
This is the same issue as in 
https://github.com/PeaceGeeksSociety/Aid-Watch/issues/17

it is better to have high quality photos, please advice which method should we use

**Comment by PeaceGeeks** [comment]
Requested new images from Nora
