### ISSUE TITLE
Take Action banners to be translated into Arabic

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/Aid-Watch#18]

**Comment by beyondes** [comment]
Translated, links can be added or edited by editing the node of header photo

**Comment by abedkhooli** [comment]
I feel the div that contains individual action items in Ar is not fully
mirrored (width or margins). They cover part of the boy's image.

On Wed, Sep 2, 2015 at 12:03 PM, beyondes <notifications@github.com> wrote:

> Closed #18 <https://github.com/PeaceGeeksSociety/Aid-Watch/issues/18>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PeaceGeeksSociety/Aid-Watch/issues/18#event-398688104>
> .
>



-- 
Abed Khooli
Business Intelligence, Web Applications and Data Science Specialist
http://www.linkedin.com/in/akhooli

**Comment by PeaceGeeks** [comment]
This doesn't really matter, but different Take Action banners are used in Arabic than in English. They should be the same, but it also isn't the world if they aren't.

**Comment by beyondes** [comment]
Banners have been updated to match English version

**Comment by abedkhooli** [comment]
Can you please make sure relative URLs are accepted in Image Link field?

On Thu, Sep 3, 2015 at 2:26 AM, beyondes <notifications@github.com> wrote:

> Banners have been updated to match English version
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PeaceGeeksSociety/Aid-Watch/issues/18#issuecomment-137390035>
> .
>



-- 
Abed Khooli
Business Intelligence, Web Applications and Data Science Specialist
http://www.linkedin.com/in/akhooli

**Comment by beyondes** [comment]
You can now add relative URL, make sure to add "/" before the URL 

example "/content/stay-touch"

or to add "ar" for arabic links

exmaple "/ar/about/stay-touch"
