### ISSUE TITLE
Red blob only partially displaying in Take Action

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/Aid-Watch#34]
http://dev.awptheme.peacegeeks.org/ar/content/palestinians

<img width="1099" alt="screen shot 2015-08-30 at 11 12 36 pm" src="https://cloud.githubusercontent.com/assets/2263033/9573080/ad649966-4f6c-11e5-8529-022cfffde5cb.png">

**Comment by PeaceGeeks** [comment]
Also 
http://dev.awptheme.peacegeeks.org/ar/content/global-citizens
http://dev.awptheme.peacegeeks.org/ar/content/aid-actors

**Comment by beyondes** [comment]
Fixed, it display well now
