### ISSUE TITLE
3 discussions on arabic site but only 2 on english - how many should there be? 

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/Aid-Watch#42]

**Comment by abedkhooli** [comment]
unpublished one in Ar, as in En. So should be similar now.

On Tue, Sep 1, 2015 at 6:12 AM, Renee Black <notifications@github.com>
wrote:

> Assigned #42 <https://github.com/PeaceGeeksSociety/Aid-Watch/issues/42>
> to @abedkhooli <https://github.com/abedkhooli>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PeaceGeeksSociety/Aid-Watch/issues/42#event-397343789>
> .
>



-- 
Abed Khooli
Business Intelligence, Web Applications and Data Science Specialist
http://www.linkedin.com/in/akhooli
