### ISSUE TITLE
Social media shares not behaving as expected on News

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/Aid-Watch#46]
http://dev.awptheme.peacegeeks.org/news

Facebook generate a warning, while Twitter works, but I expected a default tweet - I can't see a place to enter that on the node. How is this supposed to work. 

<img width="754" alt="screen shot 2015-09-01 at 9 43 02 am" src="https://cloud.githubusercontent.com/assets/2263033/9610378/fbf23760-508d-11e5-8d7b-607364fb975a.png">
<img width="973" alt="screen shot 2015-09-01 at 9 42 51 am" src="https://cloud.githubusercontent.com/assets/2263033/9610379/fbf3b2a2-508d-11e5-9a0d-4bec33b8e6fd.png">

**Comment by beyondes** [comment]
This problem We think it appeared because the website is still under http password protection, can you remove this protection to test and let us know

**Comment by abedkhooli** [comment]
I did not test FB, but Twitter does not work on glimpses, blogs and news
(should capture link in addition to title). See how it works on Fundamental
questions (
http://dev.awptheme.peacegeeks.org/content/who-responsible-rebuilding-gaza)

On Wed, Sep 2, 2015 at 12:22 PM, beyondes <notifications@github.com> wrote:

> This problem We think it appeared because the website is still under http
> password protection, can you remove this protection to test and let us know
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/PeaceGeeksSociety/Aid-Watch/issues/46#issuecomment-136994307>
> .
>



-- 
Abed Khooli
Business Intelligence, Web Applications and Data Science Specialist
http://www.linkedin.com/in/akhooli

**Comment by PeaceGeeks** [comment]
@bensinjin - can you do this when you get in?

**Comment by PeaceGeeks** [comment]
This works now that the password protection is off
