### ISSUE TITLE
Banner for one of these two pages should be different

### ISSUE THREAD

**Issue by PeaceGeeks** [PeaceGeeksSociety/Aid-Watch#48]
Both pages share a common banner but banners on each overview page should be unique 
http://dev.awptheme.peacegeeks.org/glimpses-of-daily-life-in-gaza
http://dev.awptheme.peacegeeks.org/blog

If this is easy to do, please update 'Glimpses' page with this images

![activestills_downloads_img_2_lr](https://cloud.githubusercontent.com/assets/2263033/9614783/bf965510-50a8-11e5-89f9-9c09b0d5e3ce.jpg)

I have created a Header Image already for this here, but it doesn't work
http://dev.awptheme.peacegeeks.org/content/global-voices-blog

**Comment by beyondes** [comment]
Image updated for Blog not Glimpses, is this what you meant instead? because the path was set in http://dev.awptheme.peacegeeks.org/content/global-voices-blog to be  (blog) and you name it global-voices-blog, If this is right, please close the issue, if not let us know

**Comment by PeaceGeeks** [comment]
Perfect!
